config/routes.rb
WebHooksPlayground::Application.routes.draw do
  resources :users


  resources :call_backs

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)
  match ':username/:repository/notify' => 'call_backs#notify'
  root :to => 'call_backs#index'
end

app/models/call_back.rb
class CallBack < ActiveRecord::Base
  attr_accessible :payload, :repository, :url, :username
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/call_backs_controller.rb
class CallBacksController < ApplicationController




  # POST /notify/:username/:repository
  def notify
    @call_back = CallBack.new()
    @call_back.username = username = params[:username]
    @call_back.repository = repository =  params[:repository]
    @call_back.payload = params[:payload]
    @call_back.url = authorize_notification(username,repository,request.headers['Authorization'])
   # @call_back = CallBack.new(params) would probably work, too

    respond_to do |format|
      if @call_back.save
        format.html { redirect_to @call_back, notice: 'Call back was successfully created.' }
        format.json { render json: @call_back, status: :created, location: @call_back }
      else
        format.html { render action: "new" }
        format.json { render json: @call_back.errors, status: :unprocessable_entity }
      end
    end
  end
  def authorize_notification(username,repository,sha256)
    user = User.find_by_name(username)
    return "user not found, hash #{sha256}" unless user
    token = user.token
    hash =  Digest::SHA256.hexdigest("#{username}/#{repository}#{token}")
    note = (hash == sha256) ? "AUTHORIZED " : "NOT AUTHORIZED "
    note += sha256 if sha256
    note
  end


  # GET /call_backs
  # GET /call_backs.json
  def index
    @call_backs = CallBack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @call_backs }
    end
  end

  # GET /call_backs/1
  # GET /call_backs/1.json
  def show
    @call_back = CallBack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @call_back }
    end
  end

  # GET /call_backs/new
  # GET /call_backs/new.json
  def new
    @call_back = CallBack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @call_back }
    end
  end

  # GET /call_backs/1/edit
  def edit
    @call_back = CallBack.find(params[:id])
  end

  # POST /call_backs
  # POST /call_backs.json
  def create
    @call_back = CallBack.new(params[:call_back])

    respond_to do |format|
      if @call_back.save
        format.html { redirect_to @call_back, notice: 'Call back was successfully created.' }
        format.json { render json: @call_back, status: :created, location: @call_back }
      else
        format.html { render action: "new" }
        format.json { render json: @call_back.errors, status: :unprocessable_entity }
      end
    end
  end
  




  # PUT /call_backs/1
  # PUT /call_backs/1.json
  def update
    @call_back = CallBack.find(params[:id])

    respond_to do |format|
      if @call_back.update_attributes(params[:call_back])
        format.html { redirect_to @call_back, notice: 'Call back was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @call_back.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /call_backs/1
  # DELETE /call_backs/1.json
  def destroy
    @call_back = CallBack.find(params[:id])
    @call_back.destroy

    respond_to do |format|
      format.html { redirect_to call_backs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
    #  format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
   #   format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
  #    format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @user.token = "new token"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
 #       format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
  #      format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
   #     format.json { head :no_content }
      else
        format.html { render action: "edit" }
    #    format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
    #  format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/call_backs_helper.rb
module CallBacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/call_backs/_form.html.erb
<%= form_for(@call_back) do |f| %>
  <% if @call_back.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call_back.errors.count, "error") %> prohibited this call_back from being saved:</h2>

      <ul>
      <% @call_back.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :repository %><br />
    <%= f.text_field :repository %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :payload %><br />
    <%= f.text_area :payload %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/call_backs/edit.html.erb
<h1>Editing call_back</h1>

<%= render 'form' %>

<%= link_to 'Show', @call_back %> |
<%= link_to 'Back', call_backs_path %>

app/views/call_backs/index.html.erb
<h1>Listing call_backs</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Repository</th>
    <th>Url</th>
    <th>Payload</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @call_backs.each do |call_back| %>
  <tr>
    <td><%= call_back.username %></td>
    <td><%= call_back.repository %></td>
    <td><%= call_back.url %></td>
    <td></td>
    <td><%= link_to 'Show', call_back %></td>
    <td><%= link_to 'Edit', edit_call_back_path(call_back) %></td>
    <td><%= link_to 'Destroy', call_back, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call back', new_call_back_path %>

app/views/call_backs/new.html.erb
<h1>New call_back</h1>

<%= render 'form' %>

<%= link_to 'Back', call_backs_path %>

app/views/call_backs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @call_back.username %>
</p>

<p>
  <b>Repository:</b>
  <%= @call_back.repository %>
</p>

<p>
  <b>Url:</b>
  <%= @call_back.url %>
</p>

<p>
  <b>Payload:</b>
  <%= @call_back.payload %>
</p>


<%= link_to 'Edit', edit_call_back_path(@call_back) %> |
<%= link_to 'Back', call_backs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebHooksPlayground</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td>not shown</td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Token:</b>
  not shown
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>